/* ============================================================
   字母尋寶 — 單字題庫（words.js）
   ============================================================
   ★ 如何新增單字？
     在對應類別的 words 陣列中，加入一行：
     { word: "APPLE", hint: "蘋果", emoji: "🍎" }
     word 請全部大寫英文字母

   ★ 如何新增類別？
     在 WORD_BANK 物件中加入新的項目：
     "新類別": { icon: "🎯", color: "#ff6b6b", words: [ ...單字... ] }

   ★ 遊戲會自動偵測並顯示所有類別按鈕
   ============================================================ */

var WORD_BANK = {

  "動物": {
    icon: "🐾",
    color: "#f97316",
    words: [
      { word: "CAT",       hint: "貓",    emoji: "🐱" },
      { word: "DOG",       hint: "狗",    emoji: "🐶" },
      { word: "COW",       hint: "牛",    emoji: "🐄" },
      { word: "PIG",       hint: "豬",    emoji: "🐷" },
      { word: "HEN",       hint: "母雞",  emoji: "🐔" },
      { word: "ANT",       hint: "螞蟻",  emoji: "🐜" },
      { word: "BEE",       hint: "蜜蜂",  emoji: "🐝" },
      { word: "OWL",       hint: "貓頭鷹",emoji: "🦉" },
      { word: "FOX",       hint: "狐狸",  emoji: "🦊" },
      { word: "FISH",      hint: "魚",    emoji: "🐟" },
      { word: "BIRD",      hint: "鳥",    emoji: "🐦" },
      { word: "BEAR",      hint: "熊",    emoji: "🐻" },
      { word: "LION",      hint: "獅子",  emoji: "🦁" },
      { word: "FROG",      hint: "青蛙",  emoji: "🐸" },
      { word: "DUCK",      hint: "鴨子",  emoji: "🦆" },
      { word: "WOLF",      hint: "狼",    emoji: "🐺" },
      { word: "DEER",      hint: "鹿",    emoji: "🦌" },
      { word: "CRAB",      hint: "螃蟹",  emoji: "🦀" },
      { word: "HORSE",     hint: "馬",    emoji: "🐴" },
      { word: "SHEEP",     hint: "綿羊",  emoji: "🐑" },
      { word: "TIGER",     hint: "老虎",  emoji: "🐯" },
      { word: "SNAKE",     hint: "蛇",    emoji: "🐍" },
      { word: "PANDA",     hint: "熊貓",  emoji: "🐼" },
      { word: "WHALE",     hint: "鯨魚",  emoji: "🐳" },
      { word: "EAGLE",     hint: "老鷹",  emoji: "🦅" },
      { word: "SHARK",     hint: "鯊魚",  emoji: "🦈" },
      { word: "KOALA",     hint: "無尾熊", emoji: "🐨" },
      { word: "RABBIT",    hint: "兔子",  emoji: "🐰" },
      { word: "MONKEY",    hint: "猴子",  emoji: "🐒" },
      { word: "PARROT",    hint: "鸚鵡",  emoji: "🦜" },
      { word: "TURTLE",    hint: "烏龜",  emoji: "🐢" },
      { word: "PENGUIN",   hint: "企鵝",  emoji: "🐧" },
      { word: "DOLPHIN",   hint: "海豚",  emoji: "🐬" },
      { word: "GIRAFFE",   hint: "長頸鹿", emoji: "🦒" },
      { word: "ELEPHANT",  hint: "大象",  emoji: "🐘" },
      { word: "BUTTERFLY", hint: "蝴蝶",  emoji: "🦋" },
    ]
  },

  "食物": {
    icon: "🍎",
    color: "#ef4444",
    words: [
      { word: "EGG",        hint: "蛋",    emoji: "🥚" },
      { word: "JAM",        hint: "果醬",  emoji: "🫙" },
      { word: "HAM",        hint: "火腿",  emoji: "🍖" },
      { word: "NUT",        hint: "堅果",  emoji: "🥜" },
      { word: "PIE",        hint: "派",    emoji: "🥧" },
      { word: "CORN",       hint: "玉米",  emoji: "🌽" },
      { word: "MILK",       hint: "牛奶",  emoji: "🥛" },
      { word: "RICE",       hint: "飯",    emoji: "🍚" },
      { word: "CAKE",       hint: "蛋糕",  emoji: "🎂" },
      { word: "SOUP",       hint: "湯",    emoji: "🍲" },
      { word: "MEAT",       hint: "肉",    emoji: "🥩" },
      { word: "FISH",       hint: "魚料理", emoji: "🐟" },
      { word: "TOFU",       hint: "豆腐",  emoji: "🟫" },
      { word: "BREAD",      hint: "麵包",  emoji: "🍞" },
      { word: "APPLE",      hint: "蘋果",  emoji: "🍎" },
      { word: "GRAPE",      hint: "葡萄",  emoji: "🍇" },
      { word: "PIZZA",      hint: "披薩",  emoji: "🍕" },
      { word: "CANDY",      hint: "糖果",  emoji: "🍬" },
      { word: "JUICE",      hint: "果汁",  emoji: "🧃" },
      { word: "MANGO",      hint: "芒果",  emoji: "🥭" },
      { word: "LEMON",      hint: "檸檬",  emoji: "🍋" },
      { word: "PEACH",      hint: "桃子",  emoji: "🍑" },
      { word: "ONION",      hint: "洋蔥",  emoji: "🧅" },
      { word: "SALAD",      hint: "沙拉",  emoji: "🥗" },
      { word: "PASTA",      hint: "義大利麵", emoji: "🍝" },
      { word: "SUGAR",      hint: "糖",    emoji: "🍬" },
      { word: "STEAK",      hint: "牛排",  emoji: "🥩" },
      { word: "BANANA",     hint: "香蕉",  emoji: "🍌" },
      { word: "COOKIE",     hint: "餅乾",  emoji: "🍪" },
      { word: "BURGER",     hint: "漢堡",  emoji: "🍔" },
      { word: "NOODLE",     hint: "麵條",  emoji: "🍜" },
      { word: "CHERRY",     hint: "櫻桃",  emoji: "🍒" },
      { word: "TOMATO",     hint: "番茄",  emoji: "🍅" },
      { word: "ORANGE",     hint: "柳橙",  emoji: "🍊" },
      { word: "MELON",      hint: "哈密瓜", emoji: "🍈" },
      { word: "STRAWBERRY", hint: "草莓",  emoji: "🍓" },
      { word: "WATERMELON", hint: "西瓜",  emoji: "🍉" },
    ]
  },

  "顏色": {
    icon: "🎨",
    color: "#a855f7",
    words: [
      { word: "RED",    hint: "紅色",  emoji: "🔴" },
      { word: "BLUE",   hint: "藍色",  emoji: "🔵" },
      { word: "PINK",   hint: "粉紅色", emoji: "🩷" },
      { word: "GRAY",   hint: "灰色",  emoji: "🩶" },
      { word: "GOLD",   hint: "金色",  emoji: "🌟" },
      { word: "GREEN",  hint: "綠色",  emoji: "🟢" },
      { word: "BLACK",  hint: "黑色",  emoji: "⚫" },
      { word: "WHITE",  hint: "白色",  emoji: "⚪" },
      { word: "BROWN",  hint: "棕色",  emoji: "🟤" },
      { word: "BEIGE",  hint: "米色",  emoji: "🟡" },
      { word: "PEACH",  hint: "桃色",  emoji: "🍑" },
      { word: "CORAL",  hint: "珊瑚色", emoji: "🪸" },
      { word: "TEAL",   hint: "藍綠色", emoji: "💠" },
      { word: "CYAN",   hint: "青色",  emoji: "🩵" },
      { word: "LIME",   hint: "萊姆綠", emoji: "🟢" },
      { word: "NAVY",   hint: "深藍色", emoji: "🫐" },
      { word: "IVORY",  hint: "象牙白", emoji: "🟡" },
      { word: "AMBER",  hint: "琥珀色", emoji: "🟠" },
      { word: "VIOLET", hint: "紫羅蘭色", emoji: "💜" },
      { word: "PURPLE", hint: "紫色",  emoji: "💜" },
      { word: "YELLOW", hint: "黃色",  emoji: "🟡" },
      { word: "ORANGE", hint: "橙色",  emoji: "🟠" },
      { word: "INDIGO", hint: "靛藍色", emoji: "💙" },
      { word: "SILVER", hint: "銀色",  emoji: "⭐" },
      { word: "SCARLET",hint: "鮮紅色", emoji: "🔴" },
      { word: "CRIMSON",hint: "深紅色", emoji: "❤️" },
      { word: "MAGENTA",hint: "洋紅色", emoji: "🌸" },
    ]
  },

  "學校": {
    icon: "🏫",
    color: "#3b82f6",
    words: [
      { word: "PEN",      hint: "鋼筆",   emoji: "🖊️" },
      { word: "MAP",      hint: "地圖",   emoji: "🗺️" },
      { word: "GYM",      hint: "體育館", emoji: "🏋️" },
      { word: "BOOK",     hint: "書",     emoji: "📚" },
      { word: "DESK",     hint: "桌子",   emoji: "🪑" },
      { word: "EXAM",     hint: "考試",   emoji: "📝" },
      { word: "BELL",     hint: "鐘聲",   emoji: "🔔" },
      { word: "RULE",     hint: "規則",   emoji: "📋" },
      { word: "RULER",    hint: "尺",     emoji: "📏" },
      { word: "CLASS",    hint: "班級",   emoji: "🏫" },
      { word: "GRADE",    hint: "成績/年級", emoji: "📊" },
      { word: "PAPER",    hint: "紙",     emoji: "📄" },
      { word: "CHAIR",    hint: "椅子",   emoji: "🪑" },
      { word: "PENCIL",   hint: "鉛筆",   emoji: "✏️" },
      { word: "ERASER",   hint: "橡皮擦", emoji: "🗑️" },
      { word: "SCHOOL",   hint: "學校",   emoji: "🏫" },
      { word: "LESSON",   hint: "課程",   emoji: "📖" },
      { word: "SCIENCE",  hint: "科學",   emoji: "🔬" },
      { word: "ENGLISH",  hint: "英語",   emoji: "🇬🇧" },
      { word: "HISTORY",  hint: "歷史",   emoji: "📜" },
      { word: "TEACHER",  hint: "老師",   emoji: "👩‍🏫" },
      { word: "STUDENT",  hint: "學生",   emoji: "👨‍🎓" },
      { word: "LIBRARY",  hint: "圖書館", emoji: "📚" },
      { word: "HOMEWORK", hint: "家庭作業", emoji: "📋" },
      { word: "COMPUTER", hint: "電腦",   emoji: "💻" },
      { word: "NOTEBOOK", hint: "筆記本", emoji: "📓" },
      { word: "BACKPACK", hint: "書包",   emoji: "🎒" },
      { word: "CALENDAR", hint: "月曆",   emoji: "📅" },
      { word: "SCISSORS", hint: "剪刀",   emoji: "✂️" },
      { word: "CLASSROOM",hint: "教室",   emoji: "🏫" },
    ]
  },

  "自然": {
    icon: "🌿",
    color: "#10b981",
    words: [
      { word: "SUN",      hint: "太陽",  emoji: "☀️" },
      { word: "ICE",      hint: "冰",    emoji: "🧊" },
      { word: "MUD",      hint: "泥土",  emoji: "🌫️" },
      { word: "FOG",      hint: "霧",    emoji: "🌫️" },
      { word: "MOON",     hint: "月亮",  emoji: "🌙" },
      { word: "STAR",     hint: "星星",  emoji: "⭐" },
      { word: "RAIN",     hint: "雨",    emoji: "🌧️" },
      { word: "SNOW",     hint: "雪",    emoji: "❄️" },
      { word: "WIND",     hint: "風",    emoji: "💨" },
      { word: "TREE",     hint: "樹",    emoji: "🌳" },
      { word: "LEAF",     hint: "葉子",  emoji: "🍃" },
      { word: "SEED",     hint: "種子",  emoji: "🌱" },
      { word: "ROCK",     hint: "石頭",  emoji: "🪨" },
      { word: "CAVE",     hint: "洞穴",  emoji: "🏔️" },
      { word: "LAKE",     hint: "湖",    emoji: "🏞️" },
      { word: "WAVE",     hint: "波浪",  emoji: "🌊" },
      { word: "CLOUD",    hint: "雲",    emoji: "☁️" },
      { word: "RIVER",    hint: "河流",  emoji: "🌊" },
      { word: "OCEAN",    hint: "海洋",  emoji: "🌊" },
      { word: "FLOWER",   hint: "花",    emoji: "🌸" },
      { word: "FOREST",   hint: "森林",  emoji: "🌲" },
      { word: "DESERT",   hint: "沙漠",  emoji: "🏜️" },
      { word: "ISLAND",   hint: "島嶼",  emoji: "🏝️" },
      { word: "JUNGLE",   hint: "叢林",  emoji: "🌿" },
      { word: "PLANET",   hint: "星球",  emoji: "🪐" },
      { word: "VOLCANO",  hint: "火山",  emoji: "🌋" },
      { word: "RAINBOW",  hint: "彩虹",  emoji: "🌈" },
      { word: "THUNDER",  hint: "雷",    emoji: "⛈️" },
      { word: "MOUNTAIN", hint: "山",    emoji: "⛰️" },
      { word: "WATERFALL",hint: "瀑布",  emoji: "💧" },
    ]
  },

  "身體": {
    icon: "💪",
    color: "#ec4899",
    words: [
      { word: "EYE",      hint: "眼睛",  emoji: "👁️" },
      { word: "EAR",      hint: "耳朵",  emoji: "👂" },
      { word: "ARM",      hint: "手臂",  emoji: "💪" },
      { word: "LEG",      hint: "腿",    emoji: "🦵" },
      { word: "RIB",      hint: "肋骨",  emoji: "🦴" },
      { word: "JAW",      hint: "下巴",  emoji: "😬" },
      { word: "LIP",      hint: "嘴唇",  emoji: "👄" },
      { word: "HAND",     hint: "手",    emoji: "✋" },
      { word: "FOOT",     hint: "腳",    emoji: "🦶" },
      { word: "NOSE",     hint: "鼻子",  emoji: "👃" },
      { word: "BACK",     hint: "背部",  emoji: "🧍" },
      { word: "HAIR",     hint: "頭髮",  emoji: "💇" },
      { word: "FACE",     hint: "臉",    emoji: "😊" },
      { word: "KNEE",     hint: "膝蓋",  emoji: "🦵" },
      { word: "HEEL",     hint: "腳跟",  emoji: "🦶" },
      { word: "NECK",     hint: "脖子",  emoji: "🦒" },
      { word: "CHIN",     hint: "下巴",  emoji: "😊" },
      { word: "HEAD",     hint: "頭",    emoji: "🗣️" },
      { word: "HEART",    hint: "心臟",  emoji: "❤️" },
      { word: "BRAIN",    hint: "大腦",  emoji: "🧠" },
      { word: "MOUTH",    hint: "嘴巴",  emoji: "👄" },
      { word: "THUMB",    hint: "大拇指", emoji: "👍" },
      { word: "ELBOW",    hint: "手肘",  emoji: "💪" },
      { word: "ANKLE",    hint: "腳踝",  emoji: "🦶" },
      { word: "CHEEK",    hint: "臉頰",  emoji: "😊" },
      { word: "FINGER",   hint: "手指",  emoji: "☝️" },
      { word: "SHOULDER", hint: "肩膀",  emoji: "💪" },
      { word: "STOMACH",  hint: "胃/肚子", emoji: "🫃" },
      { word: "FOREHEAD", hint: "額頭",  emoji: "🤔" },
      { word: "EYEBROW",  hint: "眉毛",  emoji: "🤨" },
    ]
  },

  "日常生活": {
    icon: "🏠",
    color: "#0ea5e9",
    words: [
      { word: "BED",      hint: "床",    emoji: "🛏️" },
      { word: "CUP",      hint: "杯子",  emoji: "☕" },
      { word: "KEY",      hint: "鑰匙",  emoji: "🔑" },
      { word: "BAG",      hint: "包包",  emoji: "👜" },
      { word: "HAT",      hint: "帽子",  emoji: "🎩" },
      { word: "COAT",     hint: "外套",  emoji: "🧥" },
      { word: "SHOE",     hint: "鞋子",  emoji: "👟" },
      { word: "SOCK",     hint: "襪子",  emoji: "🧦" },
      { word: "LAMP",     hint: "檯燈",  emoji: "💡" },
      { word: "SOFA",     hint: "沙發",  emoji: "🛋️" },
      { word: "DOOR",     hint: "門",    emoji: "🚪" },
      { word: "BOOK",     hint: "書",    emoji: "📚" },
      { word: "CLOCK",    hint: "時鐘",  emoji: "🕐" },
      { word: "CHAIR",    hint: "椅子",  emoji: "🪑" },
      { word: "TABLE",    hint: "桌子",  emoji: "🪑" },
      { word: "PHONE",    hint: "電話",  emoji: "📱" },
      { word: "RADIO",    hint: "收音機", emoji: "📻" },
      { word: "TOWEL",    hint: "毛巾",  emoji: "🏊" },
      { word: "MIRROR",   hint: "鏡子",  emoji: "🪞" },
      { word: "PILLOW",   hint: "枕頭",  emoji: "😴" },
      { word: "WALLET",   hint: "錢包",  emoji: "👛" },
      { word: "CAMERA",   hint: "相機",  emoji: "📷" },
      { word: "BOTTLE",   hint: "瓶子",  emoji: "🍶" },
      { word: "UMBRELLA", hint: "雨傘",  emoji: "☂️" },
      { word: "COMPUTER", hint: "電腦",  emoji: "💻" },
    ]
  },

};
